# FIPS 140-3 Compliance Configuration using Microsoft Go and Azure Linux:
# - Builder: mcr.microsoft.com/oss/go/microsoft/golang:1.25-azurelinux3.0
#   Microsoft's Go fork with integrated FIPS support via platform crypto libraries
# - Runtime: mcr.microsoft.com/azurelinux/base/core:3.0
#   Azure Linux base image with FIPS 140-3 compliance
# - GOFIPS140=latest: Enables FIPS mode in Microsoft's Go fork
# - CGO_ENABLED=1: Required for platform-dependent crypto (OpenSSL on Linux)
# - Reference: https://github.com/Azure/ARO-HCP/blob/main/frontend/Dockerfile

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/oss/go/microsoft/golang:1.25-azurelinux3.0 AS builder
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV CGO_ENABLED=1 GOFIPS140=latest

COPY . /go/src/github.com/vmware-tanzu/velero

WORKDIR /go/src/github.com/vmware-tanzu/velero

RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod=mod -ldflags '-X github.com/vmware-tanzu/velero/pkg/buildinfo.Version=oadp-1.5' -o /go/src/velero github.com/vmware-tanzu/velero/cmd/velero
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod=mod -o /go/src/velero-restore-helper github.com/vmware-tanzu/velero/cmd/velero-restore-helper
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod=mod -o /go/src/velero-helper github.com/vmware-tanzu/velero/cmd/velero-helper

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/oss/go/microsoft/golang:1.25-azurelinux3.0 AS restic-builder
ARG BUILDPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV APP_ROOT=/opt/app-root
ENV GOPATH=$APP_ROOT
ENV CGO_ENABLED=1 GOFIPS140=latest

RUN mkdir -p $APP_ROOT/src/github.com/restic \
    && cd $APP_ROOT/src/github.com/restic \
    && git clone https://github.com/konveyor/restic -b oadp-1.5

WORKDIR $APP_ROOT/src/github.com/restic/restic

RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -mod=mod -o $APP_ROOT/src/restic github.com/restic/restic/cmd/restic

FROM mcr.microsoft.com/azurelinux/base/core:3.0
RUN tdnf -y update && tdnf -y install nmap-ncat tzdata && tdnf clean all
COPY --from=builder /go/src/velero velero
COPY --from=builder /go/src/velero-restore-helper velero-restore-helper
COPY --from=builder /go/src/velero-helper velero-helper
COPY --from=restic-builder /opt/app-root/src/restic /usr/bin/restic

RUN mkdir -p /home/velero
RUN chmod -R 777 /home/velero

USER 65534:65534
ENV HOME=/home/velero

ENTRYPOINT ["/velero"]
