name: Add issues with a milestone to the milestone's board

on:
  issues:
    types: [milestoned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.2
        with:
          # Do NOT add PRs to the board, as that's duplication. Their corresponding issue should be on the board.
          if: ${{ !github.event.issue.pull_request }}
          project: "${{ github.event.issue.milestone.title }}"
          column: "To Do"
          repo-token: ${{ secrets.GH_TOKEN }}

